#!/usr/bin/env python3

import sys

import games_list
import config

# Load and check the input configuration
game_conf = config.load_game_conf()
if game_conf is None:
  sys.exit(1)

sources = config.load_source_conf()
if sources is None:
  sys.exit(1)

games = games_list.reload(sources)

print(games)
